---
name: Playwright Tests 🚀 🚀 🚀
run-name: ➡️ ${{ github.ref }} - ${{ github.event_name }} (${{ github.event.action }})

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npm run test
    - name: Generate allure report
      run: npm run generate:allure:report
    - name: Upload allure report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: allure-report
